print("Que sale de la cruza de un mono y un pato?")
input()
print("Un monopatin||\n")
print("Porqué los pájaros vuelan pa\'l sur?")
input()
print("pues porque caminando demorarían demasiado||\n")
print("En qué se parecen, una familia, un bombero y un barco?")
input()
print("En que el bombero y el barco tienen casco.")
print("Y la familia?", end = " ")
print("Bien gracias!!")
